### ISSUE TITLE
subprocess.call runs /bin/sh shell, and thus "source" is unknown

### ISSUE THREAD

**Issue by johannct** [lsst-camera-dh/release#3]
so l.114 of bin/install.py fails with 'source' not found error : subprocess.call does not run in a bash shell per default. Proposal  for l.114 :
        subprocess.call(commands, shell=True, executable="/bin/bash")
Likewise for the other instances of the same problem in the script.

**Comment by heather999** [comment]
I think I see a similar issue when the installation script reaches the jh_test.  
added /nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/anaconda/ .3.0/bin to PATH
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/dev/0.0.7/Modules/3.2.10/init/bash_completion: line 14: syntax error near unexpected token `('
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/dev/0.0.7/Modules/3.2.10/init/bash_completion: line 14:`   comm -23  <(_module_avail|sort)  <(tr : '\n' <<<${LOADEDMODULES}|sort)'
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/dev/0.0.7/Modules/3.2.10/init/bash_completion: line 14: warning: syntax errors in . or eval will cause future versions of the shell to abort as Posix requires
These errors/warnings disappear if the 3rd argument setting executable to /bin/bash is added.  I didn't have this problem when running locally on my own machine - I suspect because bash is my default shell there, and it's not at SLAC.

**Comment by heather999** [comment]
I think this is fixed now in master.  Just followed Johann's advice :)
